fool_game/fool_game/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('register/', include("register.urls")),
    path('admin/', admin.site.urls),
]

fool_game/register/urls.py
from django.urls import path

from . import views

app_name = "register"
urlpatterns = [
    path("", views.index, name="index"),
    path("user/<int:user_id>/", views.get_user, name="get_user")
]

fool_game/register/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    login = models.CharField(name="login", max_length=32)
    password = models.CharField(max_length=32)

    def __str__(self):
        return "User by login: " + self.login

fool_game/register/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .models import User

from django.http import HttpResponse


def index(request):

    users = User.objects.all()
    context = {
        "users" : users
    }

    return render(request, "register/index.html", context)


def get_user(request, user_id):
    
    #user = User.objects.get(pk=user_id)
    user = get_object_or_404(User, pk=user_id)
    context = {
        "user" : user
    }

    return render(request, "register/get_user.html", context)

fool_game/register/templates/register/get_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <a href="/register/">назад</a>

    <h1>{{ user.login }}</h1>
    <h1>{{ user.password }}</h1>

</body>
</html>

fool_game/register/templates/register/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Привет мир. Это страница регистрации. Все пользователи:</h1>

    {% if users %}

    <ul>
        {% for user in users %}
        <li><a href="{% url 'register:get_user' user.id %}">{{ user.login }}</a></li>
        {% endfor %}
    </ul>

    {% else %}

    <h2>Пользователей нет.</h2>

    {% endif %}

</body>
</html>